config/routes.rb
Rails.application.routes.draw do
  resources :demos
  get 'render/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "render#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: %i[ show edit update destroy ]

  # GET /demos or /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1 or /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos or /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to demo_url(@demo), notice: "Demo was successfully created." }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1 or /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to demo_url(@demo), notice: "Demo was successfully updated." }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1 or /demos/1.json
  def destroy
    @demo.destroy!

    respond_to do |format|
      format.html { redirect_to demos_url, notice: "Demo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def demo_params
      params.require(:demo).permit(:name, :text, :description)
    end
end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/views/demos/_demo.html.erb
<div id="<%= dom_id demo %>">
  <p>
    <strong>Name:</strong>
    <%= demo.name %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= demo.text %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= demo.description %>
  </p>

</div>

app/views/demos/_form.html.erb
<%= form_with(model: demo) do |form| %>
  <% if demo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
        <% demo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing demo</h1>

<%= render "form", demo: @demo %>

<br>

<div>
  <%= link_to "Show this demo", @demo %> |
  <%= link_to "Back to demos", demos_path %>
</div>

app/views/demos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Demos</h1>

<div id="demos">
  <% @demos.each do |demo| %>
    <%= render demo %>
    <p>
      <%= link_to "Show this demo", demo %>
    </p>
  <% end %>
</div>

<%= link_to "New demo", new_demo_path %>

app/views/demos/new.html.erb
<h1>New demo</h1>

<%= render "form", demo: @demo %>

<br>

<div>
  <%= link_to "Back to demos", demos_path %>
</div>

app/views/demos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @demo %>

<div>
  <%= link_to "Edit this demo", edit_demo_path(@demo) %> |
  <%= link_to "Back to demos", demos_path %>

  <%= button_to "Destroy this demo", @demo, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/render/index.html.erb
<main class="container">
  <div class="row text-center justify-content-center">
    <div class="col">
      <h1 class="display-4">Hello World! This is Nayan Bhalerao</h1>
    </div>
  </div>
</main>